name: Check GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Docker Secrets
        run: |
          echo "USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
